version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - rag-network

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
