version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - rag-network

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rag-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: rag-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    networks:
      - rag-network


  prometheus:
      image: prom/prometheus
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
        - "9090:9090"
      networks:
        - rag-network

  grafana:
      image: grafana/grafana:latest
      container_name: rag-grafana
      ports:
        - "3001:3000"  # Access Grafana at http://localhost:3001
      depends_on:
        - prometheus
      networks:
        - rag-network
      volumes:
        - grafana-storage:/var/lib/grafana

volumes:
  vector-data:
  grafana-storage:


networks:
  rag-network:
    driver: bridge
