version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - rag-network

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - rag-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: rag-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
